services:
  - type: web
    name: oncomech-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: python server.py
    autoDeploy: true
